### PR TITLE
Update authy client

### PR DESCRIPTION
**Pull request by hortega**

### CODE REVIEW

**Comment by dprothero** [comment]
After struggling mightily to get postgres up and running on my Ruby container, I ran into the error below. @hortega or @po5i can we set this project up to use sqlite like the Rails and Flask examples?

```
root@238302dfdc2b:/authy2fa-sinatra# bundle exec rake
/usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/connection.rb:79:in `initialize': fe_sendauth: no password supplied (DataObjects::ConnectionError)
        from /usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/connection.rb:79:in `new'
        from /usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:181:in `block in new'
        from /usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:176:in `synchronize'
        from /usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:176:in `new'
        from /usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/pooling.rb:121:in `new'
        from /usr/local/bundle/gems/data_objects-0.10.17/lib/data_objects/connection.rb:68:in `new'
        from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:251:in `open_connection'
        from /usr/local/bundle/gems/dm-transactions-1.2.0/lib/dm-transactions/adapters/dm-do-adapter.rb:69:in `open_connection'
        from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:276:in `with_connection'
        from /usr/local/bundle/gems/dm-do-adapter-1.2.0/lib/dm-do-adapter/adapter.rb:61:in `execute'
        from /usr/local/bundle/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:60:in `ensure in without_notices'
        from /usr/local/bundle/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:60:in `without_notices'
        from /usr/local/bundle/gems/dm-migrations-1.2.0/lib/dm-migrations/adapters/dm-postgres-adapter.rb:18:in `upgrade_model_storage'
        from /usr/local/bundle/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:73:in `upgrade_model_storage'
        from /usr/local/bundle/gems/dm-migrations-1.2.0/lib/dm-migrations/auto_migration.rb:145:in `auto_upgrade!'
        from /authy2fa-sinatra/app.rb:21:in `<top (required)>'
        from /authy2fa-sinatra/spec/spec_utils.rb:4:in `require_relative'
        from /authy2fa-sinatra/spec/spec_utils.rb:4:in `<top (required)>'
        from /authy2fa-sinatra/spec/requests/callback_spec.rb:1:in `require_relative'
        from /authy2fa-sinatra/spec/requests/callback_spec.rb:1:in `<top (required)>'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
        from /usr/local/bundle/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
        from /usr/local/bundle/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
```

**Comment by po5i** [comment]
Working on that

**Comment by po5i** [comment]
@dprothero done!

**Comment by dprothero** [comment]
@po5i I still cannot install the gem dependencies. Here's the error I get while running `bundle` in the `ruby:latest` docker image:

```
root@de8cf244f6d6:/authy2fa-sinatra# bundle
Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/authy/authy-ruby.git
Fetching rake 10.5.0
Installing rake 10.5.0
Fetching i18n 0.7.0
Installing i18n 0.7.0
Fetching json 1.8.3
Installing json 1.8.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/json-1.8.3/ext/json/ext/generator
/usr/local/bin/ruby -r ./siteconf20180406-17-152niy8.rb extconf.rb
creating Makefile

current directory: /usr/local/bundle/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /usr/local/bundle/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c: In function 'generate_json':
generator.c:861:25: error: 'rb_cFixnum' undeclared (first use in this function)
     } else if (klass == rb_cFixnum) {
                         ^~~~~~~~~~
generator.c:861:25: note: each undeclared identifier is reported only once for each
function it appears in
generator.c:863:25: error: 'rb_cBignum' undeclared (first use in this function)
     } else if (klass == rb_cBignum) {
                         ^~~~~~~~~~
generator.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
Makefile:242: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/bundle/gems/json-1.8.3 for inspection.
Results logged to /usr/local/bundle/extensions/x86_64-linux/2.5.0/json-1.8.3/gem_make.out

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.

In Gemfile:
  activesupport was resolved to 4.2.5, which depends on
    json
```

**Comment by po5i** [comment]
@dprothero I was able to install all the gems using the following Dockerfile

```Dockerfile
FROM ruby:latest

RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD bundle exec rackup -o 0.0.0.0
```

The commands that I used to build and run the container:

- `docker build . -t authy-sinatra`
- `docker run -p 9292:9292 authy-sinatra`

Let me know if there is something that I could missed

**Pull request merged**
